// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreEntityFrameworkCodeFirstPersonelPuantaj.Models;

namespace NetCoreEntityFrameworkCodeFirstPersonelPuantaj.Migrations
{
    [DbContext(typeof(ApplicationConnectionDbString))]
    partial class ApplicationConnectionDbStringModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NetCoreEntityFrameworkCodeFirstPersonelPuantaj.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Departman");
                });

            modelBuilder.Entity("NetCoreEntityFrameworkCodeFirstPersonelPuantaj.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Carsamba")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cuma")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cumartesi")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DepatmanId")
                        .HasColumnType("int");

                    b.Property<string>("Pazar")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Pazartesi")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Persembe")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sali")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Soyad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("NetCoreEntityFrameworkCodeFirstPersonelPuantaj.Models.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Vardiya");
                });
#pragma warning restore 612, 618
        }
    }
}
